<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'AreaRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'AreaRepository.name';
  }
}
