<?php

namespace AppBundle\Repository;

/**
 * AttendantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendantRepository extends \Doctrine\ORM\EntityRepository
{
}
