<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * AttendantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendantRepository extends DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'AttendantRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'AttendantRepository.name';
  }

  public function getFaunasByAttendant($id_attendant){
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb
    ->select('f')
    ->from('AppBundle:Fauna','f')
    ->join('f.attendants', 'a')
    ->where($qb->expr()->eq('f.deleted',':state'))
    ->andWhere($qb->expr()->eq('a.id', ':id_attendant'))
    ->setParameters(array(
      'state'=>false,
      'id_attendant'=>$id_attendant
    ));
    return $qb->getQuery()->getResult();
  }
}
