<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * AttendantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendantRepository extends DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'AttendantRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'AttendantRepository.name';
  }
}