<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'CategoryRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'CategoryRepository.name';
  }
}