<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * DefaultEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultEntityRepository extends \Doctrine\ORM\EntityRepository
{
  protected static $nameClass;
  protected static $orderByAttribute;

  public function findByPage($page = 1, $max = 10)
  {
      $this->setNameClass();
      $this->setOrderByAttribute();
      $dql = $this->createQueryBuilder(self::$nameClass);
      $dql->orderBy(self::$orderByAttribute, 'DESC');

      $firstResult = ($page - 1) * $max;

      $query = $dql->getQuery();
      $query->setFirstResult($firstResult);
      $query->setMaxResults($max);

      $paginator = new Paginator($query);

      if(($paginator->count() <=  $firstResult) && $page != 1) {
          throw new NotFoundHttpException('Page not found');
      }

      return $paginator;
  }

  protected function setNameClass(){
    self::$nameClass = '';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = '';
  }
}
