<?php

namespace AppBundle\Repository;

/**
 * FASpecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FASpecieRepository extends \Doctrine\ORM\EntityRepository
{
}
