<?php

namespace AppBundle\Repository;

/**
 * FASubspecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FASubspecieRepository extends \Doctrine\ORM\EntityRepository
{
}
