<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * FaunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaunaRepository extends DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'FaunaRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'FaunaRepository.name';
  }

  protected function setQuery($arrayParams){
    $primero = false;
    //$dql = $this->createQueryBuilder(self::$nameClass);
    $dql = $this->getEntityManager()->createQuery("SELECT f FROM AppBundle:Fauna f
                                        LEFT JOIN f.attendants a
                                        WHERE a.id = 2 ");
    //armo la query en base al array1
    // foreach ($arrayParams as $key => $value) {
    //   if (!is_null($value)) {
    //     if (!$primero) {
    //       $primero = true;
    //       //Attendant = :attendant
    //       $dql->where(self::$nameClass.'.'.$key.' = :'.$key)
    //       ->setParameter($key, $value);
    //     }
    //     else {
    //       $dql->andWhere(self::$nameClass.'.'.$key.' = :'.$key)
    //       ->setParameter($key, $value);
    //     }
    //   }
    // }
    // $qb = $this->getEntityManager()->createQueryBuilder();
    //
    // $qb->select('od', 'md');
    // $qb->from('Fauna', 'od');
    // $qb->innerJoin('Attendant', 'md', \Doctrine\ORM\Query\Expr\Join::WITH, 'od.attendant = md.id');
    // $qb->leftJoin('u.friendsOf', 'mf', 'with', 'mf.gender = :male')->setParameter('male', 1)
    //$qb->where('od.attendant = ?1');
    //$qb->setParameter(1, 1);

    //->innerJoin('person.provider','provider')
    //die();
    //$dql->orderBy(self::$orderByAttribute, 'DESC');
    return $dql;
    //return $qb;
  }
}
