<?php

namespace AppBundle\Repository;

/**
 * FloraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloraRepository extends \Doctrine\ORM\EntityRepository
{
}
