<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * FLSpecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FLSpecieRepository extends DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'FLSpecieRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'FLSpecieRepository.name';
  }
}
