<?php

namespace AppBundle\Repository;

/**
 * FLSpecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FLSpecieRepository extends \Doctrine\ORM\EntityRepository
{
}
