<?php

namespace AppBundle\Repository;

/**
 * FLSubspecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FLSubspecieRepository extends \Doctrine\ORM\EntityRepository
{
}
