<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
/**
 * FLSubspecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FLSubspecieRepository extends  DefaultEntityRepository
{
  public function setNameClass()
  {
    self::$nameClass = 'FLSubspecieRepository';
  }

  protected function setOrderByAttribute(){
    self::$orderByAttribute = 'FLSubspecieRepository.name';
  }
}
