<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 class UserRepository extends DefaultEntityRepository
 {
   public function setNameClass()
   {
     self::$nameClass = 'UserRepository';
   }

   protected function setOrderByAttribute(){
     self::$orderByAttribute = 'UserRepository.username';
   }
 }
