<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3om4aou\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3om4aou/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3om4aou.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3om4aou\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3om4aou\appProdProjectContainer(array(
    'container.build_hash' => '3om4aou',
    'container.build_id' => 'e4f39aa2',
    'container.build_time' => 1540497675,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3om4aou');
