<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwx0g8x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwx0g8x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMwx0g8x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMwx0g8x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMwx0g8x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mwx0g8x',
    'container.build_id' => '2f48b07f',
    'container.build_time' => 1543264618,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwx0g8x');
