<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDi5otmw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDi5otmw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDi5otmw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDi5otmw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDi5otmw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Di5otmw',
    'container.build_id' => 'b7959d96',
    'container.build_time' => 1540771739,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDi5otmw');
